"""Self-Modifying Memory (SMM) — Titan Memory augmented with a meta-network.

Extends TitanMemory with a small meta-network g_ψ that generates additive
weight modifications, implementing the SMM concept from Jafari 2025:

    M_t^(l)(k_t) = θ_t^(l) k_t + Δθ_t^(l) ⊙ v_t

where Δθ_t^(l) = g_ψ(k_t, v_t, c_t^(l)) is generated by the meta-network,
and c_t^(l) is a learned per-level context embedding.

The meta-network ψ is optimised by the outer-loop (standard backprop through
the main loss), while the base memory θ is updated both by DGD (inner-loop)
and outer-loop (via meta-gradient chain from TitanMemory).

Design:
    - Composes (wraps) an existing TitanMemory — reuses all DGD machinery,
      active-weight management, surprise signals, and diagnostics.
    - Adds a lightweight meta-network (2-layer MLP) and per-level context.
    - The meta-network output modulates the retrieval before output projection.
    - All CL lifecycle hooks are delegated to the wrapped TitanMemory.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch import Tensor

from src.models.hope.titan_memory import TitanMemory, TitanMemoryConfig

log = logging.getLogger(__name__)

# ──────────────────────────────────────────────────────────────────────────
# Configuration
# ──────────────────────────────────────────────────────────────────────────

DEFAULT_ETA_INIT = -3.0    # softplus(-3) ≈ 0.049
DEFAULT_ALPHA_INIT = 2.0   # sigmoid(2) ≈ 0.88


@dataclass
class SMMConfig:
    """Configuration for a Self-Modifying Memory module.

    Attributes:
        dim: Feature dimension.
        titan_hidden_multiplier: Titan MLP hidden dim multiplier.
        titan_layers: Number of layers in Titan MLP.
        titan_activation: Activation function for Titan memory.
        titan_grad_clip_inner: Gradient clip for inner-loop DGD.
        titan_grad_clip_backward: Max gradient norm for DGD backward path.
        titan_detach_interval: Detach memory graph every N steps (0 = never).
        meta_hidden_dim: Hidden dimension of meta-network g_ψ.
            If None, defaults to dim.
        meta_activation: Activation for meta-network.
        level_index: Index of this level in the hierarchy (for context init).
    """

    dim: int = 384
    titan_hidden_multiplier: int = 2
    titan_layers: int = 2
    titan_activation: str = "gelu"
    titan_grad_clip_inner: float = 1.0
    titan_grad_clip_backward: float = 1.0
    titan_detach_interval: int = 0
    meta_hidden_dim: int | None = None
    meta_activation: str = "gelu"
    level_index: int = 0


# ──────────────────────────────────────────────────────────────────────────
# Meta-network
# ──────────────────────────────────────────────────────────────────────────


class MetaNetwork(nn.Module):
    """Small MLP that generates weight modification signals Δθ.

    g_ψ(k, v, c) → Δθ ∈ R^D

    Takes concatenated key, value, and level context as input and produces
    a per-feature modulation signal. The output is applied as element-wise
    multiplication with the memory retrieval.

    Architecture: Linear(3D → H) → Act → Linear(H → D) → Tanh
    The final Tanh bounds the modulation to [-1, 1] for stability.

    Args:
        dim: Feature dimension D.
        hidden_dim: Hidden dimension H (default: D).
        activation: Activation function name.
    """

    def __init__(
        self,
        dim: int,
        hidden_dim: int | None = None,
        activation: str = "gelu",
    ) -> None:
        super().__init__()
        hidden_dim = hidden_dim or dim
        input_dim = 3 * dim  # concat(k, v, c)

        act_map = {"gelu": nn.GELU(), "silu": nn.SiLU(), "relu": nn.ReLU()}

        self.net = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            act_map.get(activation, nn.GELU()),
            nn.Linear(hidden_dim, dim),
            nn.Tanh(),  # Bound output to [-1, 1]
        )

        # Near-zero init for stable residual learning
        nn.init.zeros_(self.net[-2].bias)
        nn.init.normal_(self.net[-2].weight, std=0.01)

    def forward(self, k: Tensor, v: Tensor, context: Tensor) -> Tensor:
        """Generate weight modification signal.

        Args:
            k: [B, N, D] keys.
            v: [B, N, D] values.
            context: [D] level context embedding (broadcast over B, N).

        Returns:
            [B, N, D] modulation signal in [-1, 1].
        """
        B, N, D = k.shape
        c = context.unsqueeze(0).unsqueeze(0).expand(B, N, D)
        inp = torch.cat([k, v, c], dim=-1)  # [B, N, 3D]
        return self.net(inp)  # [B, N, D]


# ──────────────────────────────────────────────────────────────────────────
# Self-Modifying Memory
# ──────────────────────────────────────────────────────────────────────────


class SelfModifyingMemory(nn.Module):
    """Self-Modifying Memory: TitanMemory + meta-network g_ψ.

    Forward:
        1. Retrieve from TitanMemory: o = M(q)
        2. Generate modulation: Δθ = g_ψ(k, v, c^(l))
        3. Apply self-modification: output = o + Δθ ⊙ v
           (additive modulation, not replacement — preserves TitanMemory signal)

    The meta-network learns to modulate the retrieval based on the current
    input context and the level's role in the hierarchy.

    Args:
        config: SMMConfig with all settings.
    """

    def __init__(self, config: SMMConfig) -> None:
        super().__init__()
        self.config = config
        dim = config.dim

        # ─── Core TitanMemory ───
        titan_cfg = TitanMemoryConfig(
            dim=dim,
            hidden_multiplier=config.titan_hidden_multiplier,
            num_layers=config.titan_layers,
            activation=config.titan_activation,
            grad_clip_inner=config.titan_grad_clip_inner,
            grad_clip_backward=config.titan_grad_clip_backward,
            detach_interval=config.titan_detach_interval,
        )
        self.memory = TitanMemory(titan_cfg)

        # ─── Meta-network g_ψ ───
        self.meta_net = MetaNetwork(
            dim=dim,
            hidden_dim=config.meta_hidden_dim,
            activation=config.meta_activation,
        )

        # ─── Per-level context embedding c^(l) ───
        # Initialized with small random values; different levels will learn
        # distinct contexts that guide the meta-network's modulation.
        self.level_context = nn.Parameter(
            torch.randn(dim) * 0.02
        )

        # ─── Per-level learned η and α (same as Phase 8 HybridBlock) ───
        self.eta_base = nn.Parameter(torch.full((dim,), DEFAULT_ETA_INIT))
        self.alpha_base = nn.Parameter(torch.full((dim,), DEFAULT_ALPHA_INIT))

        # ─── Modulation strength (learned scalar, starts near 0) ───
        # Gate that controls how much the meta-network modulates the output.
        # Starts near zero so initial behaviour ≈ pure TitanMemory.
        self.modulation_gate = nn.Parameter(torch.tensor(-2.0))

        # ─── State ───
        self._last_surprise: Tensor | None = None

    # ─── Forward ───

    def forward(self, q: Tensor, k: Tensor, v: Tensor) -> Tensor:
        """Forward: retrieve from memory + meta-network modulation.

        Args:
            q: [B, N, D] query tokens.
            k: [B, N, D] key tokens (for DGD write and meta-network).
            v: [B, N, D] value tokens (for DGD write and meta-network).

        Returns:
            [B, N, D] self-modified memory output.
        """
        # 1. Memory retrieval
        output = self.memory(q)

        # 2. Meta-network modulation
        delta_theta = self.meta_net(k, v, self.level_context)
        gate = torch.sigmoid(self.modulation_gate)
        output = output + gate * delta_theta * v

        return output

    def update_memory(
        self,
        k: Tensor,
        v: Tensor,
        output: Tensor,
        surprise_threshold: float = 0.0,
        freeze_inner: bool = False,
    ) -> None:
        """Update memory via DGD (inner-loop).

        Computes surprise from retrieval error and applies DGD updates
        to the wrapped TitanMemory. Same logic as Phase 8 HybridBlock
        but encapsulated per-level.

        Args:
            k: [B, N, D] keys for writing.
            v: [B, N, D] values for writing.
            output: [B, N, D] current memory output (for computing error).
            surprise_threshold: Minimum surprise to trigger update.
            freeze_inner: If True, skip DGD update (eval mode).
        """
        if freeze_inner:
            return

        if not (torch.is_grad_enabled() or not self.training):
            return

        retrieval_error = v - output
        surprise = self.memory.surprise(retrieval_error)
        self._last_surprise = surprise.detach()

        # Per-feature η and α from learned parameters
        eta = F.softplus(self.eta_base)       # [D], positive
        alpha = torch.sigmoid(self.alpha_base)  # [D], in [0,1]

        # Gate update by surprise threshold
        if surprise_threshold > 0:
            update_mask = surprise > surprise_threshold
            if not update_mask.any():
                return

        B, N, D = k.shape
        eta_expanded = eta.unsqueeze(0).unsqueeze(0).expand(B, N, D)
        alpha_expanded = alpha.unsqueeze(0).unsqueeze(0).expand(B, N, D)

        self_target = self.memory.generate_self_target(v)
        self.memory.compute_and_apply_update(
            key=k,
            value=self_target,
            error_signal=surprise,
            lr=eta_expanded,
            alpha=alpha_expanded,
        )

    # ─── CL lifecycle hooks (delegate to wrapped TitanMemory) ───

    def reset_active_weights(self) -> None:
        """Reset memory to meta-learned initial state."""
        self.memory.reset_active_weights()

    def clear_active_weights(self) -> None:
        """Clear active weights (set to None)."""
        self.memory.clear_active_weights()

    def detach_active_weights(self) -> None:
        """Detach active weights from computation graph."""
        self.memory.detach_active_weights()

    def reset_diagnostics(self) -> None:
        """Reset diagnostic counters."""
        self.memory.reset_diagnostics()

    # ─── Diagnostics ───

    def get_diagnostics(self) -> dict[str, float]:
        """Get diagnostic metrics for this SMM level."""
        diag = {}
        for key, val in self.memory.get_diagnostics().items():
            diag[f"smm/{key}"] = val

        if self._last_surprise is not None:
            diag["smm/mean_surprise"] = self._last_surprise.mean().item()
            diag["smm/max_surprise"] = self._last_surprise.max().item()

        diag["smm/mean_eta"] = F.softplus(self.eta_base).mean().item()
        diag["smm/mean_alpha"] = torch.sigmoid(self.alpha_base).mean().item()
        diag["smm/modulation_gate"] = torch.sigmoid(self.modulation_gate).item()

        return diag

    def get_gradient_norm(self) -> float:
        """Compute total gradient norm of this level's parameters.

        Used by the structural evolution controller for pruning decisions.
        Returns 0.0 if no gradients are available.
        """
        total_norm_sq = 0.0
        for p in self.parameters():
            if p.grad is not None:
                total_norm_sq += p.grad.data.norm(2).item() ** 2
        return total_norm_sq ** 0.5
